baseURL = "https://tommygroshong.com/"
languageCode = "en-us"
title = "Software Ate My Brain"
theme = "tale"

pygmentsCodeFences = true

[Author] # Used in authorbox
  name = "Tommy Groshong"
  bio = "Lazy programmer with simultaneous hyperfocus and attention deficits."
  avatar = "img/tommy.jpg"

[Params]
  pygmentsCodeFences = true
  description = "Thoughts and learnings on software and how it's made" # Site Description. Used in meta description
  copyright = "Tommy Groshong Jr." # Copyright holder, otherwise will use .Site.Title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  columns = 2 # Set the number of cards columns. Possible values: 1, 2, 3
  mainSections = ["posts"] # Set main page sections
  post_meta = ["date", "categories"] # Enable post meta fields in given order
  dateFormat = "02 January 2006" # Change the format of dates

[Params.Social]
  email = "tom@groshong.software"
  github = "tgroshon"
  twitter = "tgroshon"
  stackoverflow = "2631962"
  linkedin = "thomas-groshong-2b23aa28"

[Params.Share]
  facebook = true
  twitter = true
  reddit = true
  telegram = true
  linkedin = true
  pocket = true

[outputs]
  home = ["HTML", "RSS"]
